name: Mirroring

on:
  push:
    branches:
      - main
  delete:
    branches:
      - main
  workflow_dispatch:

jobs:
  to_public_repository:
    if: github.repository == 'wearekadence/kadence-public-api-examples-internal'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url:
            git@github.com:wearekadence/kadence-public-api-examples.git
          ssh_private_key:
            ${{ secrets.KADENCE_BOT_PRIVATE_SSH_KEY }}